### ISSUE TITLE
Cant install filterpy "AttributeError: module filterpy has no attribute _version_"

### ISSUE THREAD

**Issue by MegaCocos** [rlabbe/filterpy#316]
Cant install filterpy, I have tried in two different PCs with the same error "AttributeError: module filterpy has no attribute _version_" Anybody can help with it?

![Image](https://github.com/user-attachments/assets/84dd2116-9a71-47ce-acbc-ee272f4f417b)

**Comment by tenowg** [comment]
this is probably resolved already, but i fixed by manually setting the version in setup.py on line 18, at least it installed

**Comment by MegaCocos** [comment]
> this is probably resolved already, but i fixed by manually setting the version in setup.py on line 18, at least it installed

@tenowg Not fixed, but i found other way, installing in other VENV and just copying files and it works, don't know why. All the conversation in this issue: https://github.com/bytedance/InfiniteYou/issues/23
